# Generated by Django 6.0.3 on 2026-03-13 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stitek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=100)),
                ('barva', models.CharField(max_length=7)),
                ('specialni_vyznam', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashHesla', models.CharField(max_length=255)),
                ('googleId', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prvek',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=225)),
                ('obsah', models.TextField()),
                ('smazano', models.BooleanField(default=False)),
                ('archivovano', models.BooleanField(default=False)),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('datum_upravy', models.DateTimeField(auto_now=True)),
                ('datum_zacatku', models.DateTimeField(blank=True, null=True)),
                ('datum_konce', models.DateTimeField(blank=True, null=True)),
                ('souvisejici_prvky', models.ManyToManyField(blank=True, to='app.prvek')),
                ('stitky', models.ManyToManyField(blank=True, to='app.stitek')),
                ('vlastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uzivatel')),
            ],
        ),
        migrations.AddField(
            model_name='stitek',
            name='vlastnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uzivatel'),
        ),
        migrations.CreateModel(
            name='Seznam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=225)),
                ('popis', models.TextField()),
                ('podseznamy', models.ManyToManyField(blank=True, related_name='nadseznamy', to='app.seznam')),
                ('prvky', models.ManyToManyField(blank=True, related_name='seznamy_prvku', to='app.prvek')),
                ('stitky', models.ManyToManyField(blank=True, related_name='seznamy_stitku', to='app.stitek')),
                ('stitkyVSeznamu', models.ManyToManyField(blank=True, related_name='seznamy_stitku_vseznamu', to='app.stitek')),
                ('vlastnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uzivatel')),
            ],
        ),
    ]
