# Generated by Django 6.0.3 on 2026-03-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_seznam_vlastnik_alter_prvek_vlastnik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prvek',
            name='obsah',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seznam',
            name='popis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
