# Generated by Django 6.0.3 on 2026-03-13 21:35

from django.db import migrations

class Migration(migrations.Migration):

    # 1. Napíšeme funkci, která data vytvoří
    def vytvor_systemove_stitky(apps, schema_editor):
        Stitek = apps.get_model('app', 'Stitek')

        # Náš seznam systémových štítků
        vychozi_stitky = [
            {'nazev': 'Důležité', 'barva': '#FF0000', 'specialni_vyznam': 'dulezite'},
            {'nazev': 'Hotovo', 'barva': '#00FF00', 'specialni_vyznam': 'hotovo'},
            {'nazev': 'Archiv', 'barva': '#808080', 'specialni_vyznam': 'archiv'},
        ]

        for data in vychozi_stitky:
            # get_or_create je super - vytvoří štítek jen tehdy, pokud tam ještě není.
            # Kdybys to spouštěl víckrát, neudělá ti to duplikáty.
            Stitek.objects.get_or_create(
                nazev=data['nazev'],
                defaults={
                    'barva': data['barva'],
                    'specialni_vyznam': data['specialni_vyznam']
                }
            )

    dependencies = [
        ('app', '0003_alter_prvek_obsah_alter_seznam_popis'),
    ]

    operations = [
        migrations.RunPython(vytvor_systemove_stitky)
    ]
