# Generated by Django 6.0.3 on 2026-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20260313_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='seznam',
            name='velikostni_typ',
            field=models.CharField(choices=[('malý', 'Malý'), ('střední', 'Střední'), ('velký', 'Velký')], default='střední', max_length=20),
        ),
    ]
